### ISSUE TITLE
paying entity list

### ISSUE THREAD

**Issue by TomGang** [baansconsulting/Wolfe#10]
1. can you please remove the 3 records highlighted below and change any invoices referencing them to name below them.
2. can you please have this list be sorted by paying entity name (alphabetical)

![image](https://cloud.githubusercontent.com/assets/17777303/13793396/11f0d83a-eacd-11e5-90a7-19fda7af2b69.png)

**Comment by baansconsulting** [comment]
updated the transactions and deleted the 3 entries from paying entity master

**Comment by TomGang** [comment]
looks good. thank you!
