### ISSUE TITLE
sale list - cleanup

### ISSUE THREAD

**Issue by TomGang** [baansconsulting/Wolfe#12]
can you please let me know if there are any records associated with the highlighted people below. If no records are linked, please delete the yellow entries below.
further, can you add the abiliity for me to delete them (similiar to deleting invoices, need to make certain that no records are linked before deleting. Only an "admin" can delete)

![image](https://cloud.githubusercontent.com/assets/17777303/13813294/26ced588-eb57-11e5-9fc8-2db4feb3b1de.png)

**Comment by baansconsulting** [comment]
the system has been implemented. please test and delete unwanted records

**Comment by TomGang** [comment]
works perfect. The only thing is for sales code RTC- when trying to delete the RR code for RTC (under sales, not trader- he is should be listed under traders) it tells me that records are assoicated with RTC. But when I search for him on the coverages page, it says no records.
What is the best way to identify what records are associated with RTC so I can update them?

![image](https://cloud.githubusercontent.com/assets/17777303/13920560/0e973dd8-ef4a-11e5-85d1-1427a7b810f0.png)
