### ISSUE TITLE
duplicate subaccounts - Institutional Capital, LLC

### ISSUE THREAD

**Issue by TomGang** [baansconsulting/Wolfe#14]
it looks like all of the trading subaccounts for Institional Capital LLC are in the db 2x. I assume we should delete the dupes and make sure no records are associated with that one?

![image](https://cloud.githubusercontent.com/assets/17777303/13814599/4c6cdc80-eb5d-11e5-88d5-a77e7c0dac8e.png)

**Comment by baansconsulting** [comment]
done

**Comment by TomGang** [comment]
look good. thank you!
