### ISSUE TITLE
coverages

### ISSUE THREAD

**Issue by TomGang** [baansconsulting/Wolfe#15]
it looks like if we update coverages from the customer >>> update coverages page the updates aren't pushing out to the invoices for that customer or the subaccounts.
we used the update coverages page to change CBRE from JGZ to EWR effective 1/1/16. I can see the change in the update coverages page, but not on the subaccount detail or invoice pages.

![image](https://cloud.githubusercontent.com/assets/17777303/13815870/b0046b8c-eb62-11e5-9c64-36d095e4901e.png)

![image](https://cloud.githubusercontent.com/assets/17777303/13815915/d02474ca-eb62-11e5-972d-fcbbd4c3f9e2.png)

![image](https://cloud.githubusercontent.com/assets/17777303/13815834/80f55234-eb62-11e5-9e2d-2fd2f388f950.png)

**Comment by baansconsulting** [comment]
This functionality is not there in MS Access currently. Need to discuss

**Comment by TomGang** [comment]
Can we discuss today? I am available for the next 1.5 hours....

**Comment by baansconsulting** [comment]
I have scheduled a meeting, please advice thanks Bhavna

**Comment by baansconsulting** [comment]
implemented on server

**Comment by TomGang** [comment]
it will not move past the below pop-up if I hit Yes...
it still shows the should be 100 error message in the background, not sure if that has anything to do with the problem..

![image](https://cloud.githubusercontent.com/assets/17777303/13928872/e2eb450c-ef6d-11e5-8d61-6144d77e4d59.png)
