### ISSUE TITLE
"from date" on customer page

### ISSUE THREAD

**Issue by TomGang** [baansconsulting/Wolfe#16]
question- how difficult would it be to change it so that the From Date below is only associated with the status? Basically, I am noticing the we often have to change details for a customer (address fields) and having the advance the "from date" shouldn't matter. I don't need to know the date of an address change or manger type. I would only ever care the date that the status changed. Let me know if you want to discuss tomorrow...

![image](https://cloud.githubusercontent.com/assets/17777303/13860988/64c0884a-ec61-11e5-9870-0c25ba34d0d1.png)

**Comment by baansconsulting** [comment]
Done. and implemented on the server

**Comment by TomGang** [comment]
perfect. thank you!
