### ISSUE TITLE
customer name change

### ISSUE THREAD

**Issue by TomGang** [baansconsulting/Wolfe#17]
I remember we discussed why we aren't able to change the name of a customer... but i think it would be helpful to be able to.
Can you please update Sankaty’s name in your system from Sankaty Advisors, LLC to Sankaty Advisors, LP?  

Thanks,
Tom

**Comment by baansconsulting** [comment]
the name has to be changed for both subaccount and customer? please confirm

**Comment by TomGang** [comment]
There will be times when we would to change the name for various reasons, including the client is rebranding with a new name (but we want to keep the history), or perhaps we had the name spelled wrong and want to fix it. I already have the ability in the db to change the main customer name, but cannot change the name at the customer level or the subaccount...

Ideally, I would like to be able to change both customers and subaccounts, but I can live without changing subaccounts if you recommend not being able to. (I can just open up a new subaccount if needed)
