### ISSUE TITLE
Cobalt coverages - 

### ISSUE THREAD

**Issue by TomGang** [baansconsulting/Wolfe#18]
when trying to see the account details for any of the 3 sub accounts for cobalt, we receive the following error:
![image](https://cloud.githubusercontent.com/assets/17777303/13931254/d64f001c-ef78-11e5-91d7-91675126de79.png)

I believe it has to do with when we just tried to change the coverages as of 1/1/16 (the other accounts we changed all work, just not cobalt)

**Comment by baansconsulting** [comment]
implemented

**Comment by TomGang** [comment]
works now, thank you
