### ISSUE TITLE
adding sales and trading short names to users

### ISSUE THREAD

**Issue by TomGang** [baansconsulting/Wolfe#19]
when trying to add all the sales and trader short names to pryans@wolferesearch.com  I receive the following error:

![image](https://cloud.githubusercontent.com/assets/17777303/13933449/a9942d94-ef83-11e5-8c1c-4e6709c21e02.png)

**Comment by baansconsulting** [comment]
implemented on server

**Comment by TomGang** [comment]
looks to be working now. thank you!
