### ISSUE TITLE
subaccount page

### ISSUE THREAD

**Issue by TomGang** [baansconsulting/Wolfe#2]
account number isn't labelled as a required field, but when I try to save without it, it's requiring it. (Should not be a required field for quickbook accounts)

![image](https://cloud.githubusercontent.com/assets/17777303/13756946/a6b10a1a-e9f8-11e5-9010-cbc4a1907cb5.png)

**Comment by baansconsulting** [comment]
fixed

**Comment by TomGang** [comment]
works now. thanks
