### ISSUE TITLE
forgot password button (on signin page)

### ISSUE THREAD

**Issue by TomGang** [baansconsulting/Wolfe#20]
I received the following error when testing the forgot password button
![image](https://cloud.githubusercontent.com/assets/17777303/13933615/7892ca4c-ef84-11e5-9ca9-78618319e600.png)

**Comment by baansconsulting** [comment]
On this we have to buy license of sendgrid which will be used to send email. As email functionality is working on our local development but not on server. Email functionality will any required in future for invoicing...correct?

https://sendgrid.com

https://sendgrid.com/pricing

**Comment by TomGang** [comment]
I wouldn't expect us to generate more than 1-2 emails a month from this (at most), no need for a subscription service like sendgrid.
Are we able to have an email send to me (or my team) and then we manually go in and reset their password?

**Comment by baansconsulting** [comment]
ok, then we can provide option for you as Admin to update password

**Comment by TomGang** [comment]
sounds good, should we open up a new item for this change?

**Comment by baansconsulting** [comment]
yes please
