### ISSUE TITLE
page break before grand totals

### ISSUE THREAD

**Issue by TomGang** [baansconsulting/Wolfe#21]
for the following reports, can you please put in a page break before the grand totals (so the last person doesn't see them)

Trading reports:
Daily Comm By Trader Report
Daily Comm By Sale Report
MTD QTD YTD ITD Trader CustomerTotals Report
MTD QTD YTD ITD Sales CustomerTotals Report

![image](https://cloud.githubusercontent.com/assets/17777303/13953450/6432228a-f012-11e5-8a0a-33f0b8e1bc3a.png)

**Comment by baansconsulting** [comment]
done

**Comment by TomGang** [comment]
please make sure the column headings are shown on the pages with the grand totals... looks like they got dropped off on most the reports.

**Comment by TomGang** [comment]
looks good
