### ISSUE TITLE
report name

### ISSUE THREAD

**Issue by TomGang** [baansconsulting/Wolfe#23]
can you please rename the following report from:
MTD QTD YTD ITD Trader Totals-Ad Hoc
MTD QTD YTD ITD Sales Totals-Ad Hoc

to be 
MTD QTD YTD ITD Trader Summary
MTD QTD YTD ITD Sales Summary

**Comment by baansconsulting** [comment]
done

**Comment by TomGang** [comment]
I receive the following errors when trying to open these reports now:

![image](https://cloud.githubusercontent.com/assets/17777303/14108435/64eea18e-f58b-11e5-8686-ed858ef30810.png)

![image](https://cloud.githubusercontent.com/assets/17777303/14108446/7731c7a4-f58b-11e5-84e7-288dfaea39ef.png)

**Comment by baansconsulting** [comment]
done

**Comment by TomGang** [comment]
look good. thanks
