### ISSUE TITLE
Customer Summary report

### ISSUE THREAD

**Issue by TomGang** [baansconsulting/Wolfe#28]
The Total Revenue YTD is wrong- I have attached the file from access and the file from the SQL db so you can investigate
[CustomerSummary_Report.pdf](https://github.com/baansconsulting/Wolfe/files/186013/CustomerSummary_Report.pdf)
[rptCustomerSummary_20162303085856.pdf](https://github.com/baansconsulting/Wolfe/files/186016/rptCustomerSummary_20162303085856.pdf)

**Comment by baansconsulting** [comment]
implemented on server

**Comment by TomGang** [comment]
fixed, thanks
