### ISSUE TITLE
sales list

### ISSUE THREAD

**Issue by TomGang** [baansconsulting/Wolfe#29]
for "Peter Gennari", can you change the sales coverage name to be "Gennari, Peter" to be consistant with everyone else. If possible, i would like the ability to change the Sales Coverage name field (same goes for trader page)

![image](https://cloud.githubusercontent.com/assets/17777303/14017841/91955adc-f1a0-11e5-9639-cbab8c1db131.png)

![image](https://cloud.githubusercontent.com/assets/17777303/14017877/cb25da56-f1a0-11e5-907c-09a5474f1019.png)

**Comment by baansconsulting** [comment]
done

**Comment by TomGang** [comment]
Peter was fixed. I cannot change the name in Sales Coverage, is that going to be updated so I can modify that box?

**Comment by baansconsulting** [comment]
will provide functionality later

**Comment by TomGang** [comment]
fixed. thanks
