### ISSUE TITLE
invoice 8790 dupe on QB YTD Report

### ISSUE THREAD

**Issue by TomGang** [baansconsulting/Wolfe#3]
because invoice 8790 has different period start dates, it appears to be duplicated on the report below.

![image](https://cloud.githubusercontent.com/assets/17777303/13757100/495b5f54-e9f9-11e5-9a90-981216cbe167.png)

**Comment by baansconsulting** [comment]
this is not a defect. All the invoice will be shown here. We can discuss more in meeting

**Comment by TomGang** [comment]
there were 3 records for the invoice, but only 1 record for the payment. This report should only be showing payments (so the 24k 1x not 2x)

![image](https://cloud.githubusercontent.com/assets/17777303/13784493/d807e766-eaa5-11e5-96fd-0a727b5595cf.png)

**Comment by baansconsulting** [comment]
Invoice Start Date(11/01/2015) ,Invoice End Date(12/01/2015)  should be equal Date . This will solve the issue. If you still face any challenge we can discuss

**Comment by TomGang** [comment]
It would be good to be able to have various invoice start and end dates for various records on an invoice, this can be something we discuss and fix in the future. For now, I just changed the start and end dates to be the same and it worked.

**Comment by baansconsulting** [comment]
I have changed the label status to "change request" so that we can cater in future and we can track
