### ISSUE TITLE
Independent Franchise Partners

### ISSUE THREAD

**Issue by TomGang** [baansconsulting/Wolfe#30]
It looks like this account was incorrectly associated with 1832 Asset Mangement. Can you break that connection and make it linked to a main customer with the same name as the customer (Independent Franchise Partners)
![image](https://cloud.githubusercontent.com/assets/17777303/14092865/cad2f910-f517-11e5-96ca-23a89e4f7f1d.png)

**Comment by baansconsulting** [comment]
done

**Comment by TomGang** [comment]
Can you also remove the “to date” for 1832 below. Looks like you can remove the one row and just have the first one with a from date of 4/1/10 to  current (assuming there are no records that would get messed up)
![image](https://cloud.githubusercontent.com/assets/17777303/14143511/a608ac36-f659-11e5-848b-f7f29730a96a.png)

**Comment by TomGang** [comment]
fixed. thanks
