### ISSUE TITLE
import subaccounts not working

### ISSUE THREAD

**Issue by TomGang** [baansconsulting/Wolfe#34]
I receive the following error when trying to import subaccounts:
![image](https://cloud.githubusercontent.com/assets/17777303/14174788/d91fc26a-f714-11e5-82e2-713eff025142.png)

I tried both Mutual of America and highland Capital
[Highland.xlsx](https://github.com/baansconsulting/Wolfe/files/197538/Highland.xlsx)
[Mutual.xlsx](https://github.com/baansconsulting/Wolfe/files/197539/Mutual.xlsx)

Further, searching for the client name isn't working. Please also sort the client list alphabetically

**Comment by baansconsulting** [comment]
its on server and i think you have done the testing

**Comment by TomGang** [comment]
works now. thank you
