### ISSUE TITLE
invoice & payment screen

### ISSUE THREAD

**Issue by TomGang** [baansconsulting/Wolfe#37]
please adjust the state and end date box size so it doesn't cut off the year..

![image](https://cloud.githubusercontent.com/assets/17777303/14282875/956fcbb6-fb0e-11e5-857e-5da6b2c41cd8.png)

**Comment by baansconsulting** [comment]
done. implemented on server

**Comment by TomGang** [comment]
still looks like it cut-off for certain users (invoice date is the correct size, you can make the start and end date fields the same size as the invoice date
![image](https://cloud.githubusercontent.com/assets/17777303/14316151/7a973510-fbcf-11e5-87a3-54832287ae80.png)

**Comment by baansconsulting** [comment]
I am sure this time you will fine much better changes we have done and have implemented on server thanks

**Comment by TomGang** [comment]
works. thanks
