### ISSUE TITLE
trade detail

### ISSUE THREAD

**Issue by TomGang** [baansconsulting/Wolfe#39]
We tried to change the sub-account for the below trade, but now I cannot locate the trade detail for this entry. 
![image](https://cloud.githubusercontent.com/assets/17777303/14285926/4bc67fb6-fb1b-11e5-976e-f28d4f99559a.png)

![image](https://cloud.githubusercontent.com/assets/17777303/14285924/46015416-fb1b-11e5-8143-d77ddd52faf2.png)

the new account name should be changed to SACGSCO
![image](https://cloud.githubusercontent.com/assets/17777303/14285939/53866d92-fb1b-11e5-975f-c2a82d35b5bb.png)

**Comment by baansconsulting** [comment]
implemented on server.

**Comment by TomGang** [comment]
I'd be curious to learn what happened with this one, and what the fix was...

**Comment by TomGang** [comment]
so it looks like when I edit the subaccount, the trd dates are deleted.
I see this when I clicked to edit the transaction:
![image](https://cloud.githubusercontent.com/assets/17777303/14329635/647ba29e-fc0a-11e5-8a9c-2019521c8499.png)

once, I change the subaccount, the dates go blank:
![image](https://cloud.githubusercontent.com/assets/17777303/14329649/893d2152-fc0a-11e5-984d-1404bc525eae.png)

can you fix so that the dates don't get removed when making a change to this screen?
