### ISSUE TITLE
saving invoice error

### ISSUE THREAD

**Issue by TomGang** [baansconsulting/Wolfe#4]
when trying to add the below invoice, it won't let me hit save to enter the invoice details. The same thing is happening with Blackrock EMEA

![image](https://cloud.githubusercontent.com/assets/17777303/13757181/a8f790fe-e9f9-11e5-975b-ee58e99b0065.png)

![image](https://cloud.githubusercontent.com/assets/17777303/13757212/c34c5764-e9f9-11e5-81e7-3fc68d717b36.png)

**Comment by baansconsulting** [comment]
Fixed

**Comment by TomGang** [comment]
works now, thanks
