### ISSUE TITLE
subaccount page

### ISSUE THREAD

**Issue by TomGang** [baansconsulting/Wolfe#40]
for the customer name field, can you please make the box so we can search in it and sort the customer names alphabetically-

![image](https://cloud.githubusercontent.com/assets/17777303/14316510/597e8a84-fbd1-11e5-8680-05d7c72dd759.png)

**Comment by baansconsulting** [comment]
done

**Comment by TomGang** [comment]
I see the names are sorted, I was hoping to have a box that we can type in the name that we are looking for as well, but this is good enough I guess.
