### ISSUE TITLE
import subaccount section

### ISSUE THREAD

**Issue by TomGang** [baansconsulting/Wolfe#41]
The search box is currently case sensitive. Please make it so it ignores upper/lower case-

for example when searching for "ADVISORY" the following is returned:
![image](https://cloud.githubusercontent.com/assets/17777303/14493901/fc3d515e-0155-11e6-9b43-514a34b9c348.png)

but when searching for "advisory" nothing is returned:
![image](https://cloud.githubusercontent.com/assets/17777303/14493913/12905794-0156-11e6-979c-d6f471bf5974.png)

**Comment by baansconsulting** [comment]
done and implemented on server

**Comment by TomGang** [comment]
looks good, thanks
