### ISSUE TITLE
customer page

### ISSUE THREAD

**Issue by TomGang** [baansconsulting/Wolfe#6]
Can we not make email a required field for the adding a customer screen. Thanks

![image](https://cloud.githubusercontent.com/assets/17777303/13757317/451cbed2-e9fa-11e5-9fd6-ed484593eb74.png)

**Comment by baansconsulting** [comment]
Hope this can be done later not a priority point

**Comment by TomGang** [comment]
agreed. low priority

**Comment by baansconsulting** [comment]
Added new code for validation- 1 hours of change

**Comment by TomGang** [comment]
looks good. thank you.
