### ISSUE TITLE
user: pcaverly@wrs.com cannot log in

### ISSUE THREAD

**Issue by TomGang** [baansconsulting/Wolfe#7]
when trying to log in this morning he received the following error:

![image](https://cloud.githubusercontent.com/assets/17777303/13777895/336fb434-ea89-11e5-9a4d-12425a5f3c1e.png)

**Comment by baansconsulting** [comment]
When we login we are not getting any error. Can you please login and let us know?

**Comment by baansconsulting** [comment]
I tried on server using loign id "pcaverly@wrs.com" and password "company" its working fine.

**Comment by TomGang** [comment]
very strange. It works now, thank you
