### ISSUE TITLE
EC - daily avg analysis TD report

### ISSUE THREAD

**Issue by TomGang** [baansconsulting/Wolfe#8]
the number of days in period isn't calculating correctly. there have been more than 5 days month to date...
the top section is actually duplicating the week to date, month to date, quarter to date, year to date, inception to date headings over and over. I have also attached the report.
[EC_Daily_AVG_Analysis_TD (1).pdf](https://github.com/baansconsulting/Wolfe/files/173932/EC_Daily_AVG_Analysis_TD.1.pdf)

![image](https://cloud.githubusercontent.com/assets/17777303/13777990/901f550e-ea89-11e5-8820-eb0d745429c0.png)

**Comment by baansconsulting** [comment]
Can you please also share MS Access report based on this data? We can discuss more in in meeting

**Comment by TomGang** [comment]
[rptECDailyAVGAnalysisTD_20161503075408.pdf](https://github.com/baansconsulting/Wolfe/files/174165/rptECDailyAVGAnalysisTD_20161503075408.pdf)

**Comment by baansconsulting** [comment]
fixed

**Comment by baansconsulting** [comment]
just wait...updating code

**Comment by baansconsulting** [comment]
updated code on server. you can now test.

**Comment by TomGang** [comment]
looks good based on preliminary testing. I will continue to monitor for the next few days and reopen if needed. closing for now.
