### ISSUE TITLE
update coverages

### ISSUE THREAD

**Issue by TomGang** [baansconsulting/Wolfe#9]
few issues noticed when trying to update coverages.
1. something is wrong with the total PCT field, it doesn't recognize the sales percentage boxes until you click on it. and once you hit save, it goes back to 0 and  gives an error that should be 100 if we are overriding coverage for an backdate

![image](https://cloud.githubusercontent.com/assets/17777303/13793169/01fd05c6-eacc-11e5-9c65-69ccb489bfb9.png)

**Comment by baansconsulting** [comment]
done

**Comment by TomGang** [comment]
this doesn't appear to be working correctly yet. I opened up another issue with more information so I can close this one.
